fort2py = {
    # Constants
    'mterm': 'MAX_HARMONICS',
    'mbpm': 'MAX_BPM',
    'pieni': 'SMALL_VALUE',
    'zero': 'ZERO',
    'one': 'ONE',
    'two': 'TWO',
    'pi': 'PI',
    'duepi': 'TWO_PI',
    'piph': 'HALF_PI',

    # Arrays
    'txa': 'fundamental_frequencies_x',
    'tya': 'fundamental_frequencies_y',
    'tsa': 'fundamental_frequencies_s',
    'lr': 'line_references',
    'mr': 'multiplicity_references',
    'kr': 'coefficients_references',
    'etune': 'allowed_distance_to_fundamental_frequencies',
    'n_points': 'number_of_points',
    'x': 'x_coordinates',
    'xp': 'x_prime_coordinates',
    'y': 'y_coordinates',
    'yp': 'y_prime_coordinates',
    's': 's_coordinates',
    'sp': 's_prime_coordinates',
    'ox': 'ox_values',
    'ax': 'ax_values',
    'oy': 'oy_values',
    'ay': 'ay_values',
    'os': 'os_values',
    'as_': 'as_values',
    'xyz': 'phase_space_coordinates',
    'tunexyz': 'tune_coordinates',
    'amplitude': 'amplitude_values',
    'phase': 'phase_values',

    # Other Variables
    'tunex': 'tunex',
    'tuney': 'tuney',
    'tunez': 'tunez',
    'ox'   : 'ox',
    'ax'   : 'ax',
    'oy'   : 'oy',
    'ay'   : 'ay',
    'os'   : 'os',
    'as'   : 'as',
    'n': 'data_point_index',
    'narm': 'number_of_harmonics',
    'nf': 'number_of_frequencies',
    'nline': 'number_of_lines',
    'nlst': 'number_of_last_lines',
    'nrc': 'maximum_order_of_combination_of_frequencies',
    'nsus': 'number_of_subtracted_harmonics',
    'nt1': 'initial_turn_number',
    'nt2': 'final_turn_number',
    'ntot': 'total_number_of_data_files',
    'nturn': 'number_of_turns',
    'ntwin': 'number_of_twin_particles',
    'iunit': 'fortran_unit_number',
    'idam': 'dimension_of_phase_space',
    'iana': 'flag_for_full_analysis',
    'iconv': 'flag_for_linear_transformation',
    'istune': 'flag_for_fundamental_frequencies',
    'isme': 'flag_for_smear_calculation',
    'iinv': 'flag_for_invariants_calculation',
    'ir': 'flag_for_real_signal',
    'imeth': 'flag_for_windowing',
    'eps': 'tolerance_on_identification_of_frequencies',
    'nline': 'line_number'
}

py2fort = {val:key for key,val in fort2py.items()}