sussix.so: sussixNoO.f
	# python /usr/bin/f2py sussixNoO.f -c --fcompiler=intelem -m pysussix
	f2py sussixNoO.f -c --fcompiler=gnu95 -m pysussix

# sussix.so: sussix4drivexxNoO.f
#	python /usr/bin/f2py sussix4drivexxNoO.f --fcompiler=intelem -m sussix4drivexxNoO -c
